-- MVP 仓库库存库表设计：入库单/出库单/库存流水分层版
-- 数据库：MySQL 8
-- 说明：主键由 MyBatis-Plus ASSIGN_ID 生成，因此不使用 AUTO_INCREMENT。
-- 业务规则：DRAFT 可修改仓库、手工来源信息和产品明细；PENDING_CONFIRM 锁定仓库、来源和产品结构，仅允许有权限人员调整本次数量、合格数量、不合格数量和备注；CONFIRMED 后禁止修改。
-- 业务规则：确认入库单/出库单前，前端必须展示完整详情和全部产品明细，并从详情页发起二次确认，确认后才生成 stock_bill 库存流水。

USE erp;

CREATE TABLE IF NOT EXISTS warehouse (
    id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '仓库名称',
    contact_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '联系人',
    contact_phone VARCHAR(32) NOT NULL DEFAULT '' COMMENT '联系电话',
    address VARCHAR(255) NOT NULL DEFAULT '' COMMENT '仓库地址',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常，1删除',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_warehouse_code (warehouse_code),
    KEY idx_warehouse_deleted_status (deleted, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='仓库表';

CREATE TABLE IF NOT EXISTS warehouse_stock (
    id BIGINT NOT NULL COMMENT '库存ID',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码冗余',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '仓库名称冗余',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码冗余',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称冗余',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称冗余',
    stock_qty BIGINT NOT NULL DEFAULT 0 COMMENT '当前库存数量，按100倍整数存储',
    locked_qty BIGINT NOT NULL DEFAULT 0 COMMENT '锁定库存数量，按100倍整数存储',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_warehouse_stock_product (warehouse_id, product_id),
    KEY idx_warehouse_stock_product (product_id),
    KEY idx_warehouse_stock_product_code (product_code),
    KEY idx_warehouse_stock_product_name (product_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存余额表';

CREATE TABLE IF NOT EXISTS inbound_bill (
    id BIGINT NOT NULL COMMENT '入库单ID',
    inbound_no VARCHAR(64) NOT NULL COMMENT '入库单号',
    inbound_type VARCHAR(32) NOT NULL COMMENT '类型：PURCHASE_IN、SALES_RETURN、ADJUST_IN',
    source_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '来源类型：PURCHASE_ORDER、SALES_RETURN_ORDER、STOCK_ADJUST',
    source_id BIGINT DEFAULT NULL COMMENT '来源单据ID',
    source_no VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源单据号',
    source_party_id BIGINT DEFAULT NULL COMMENT '来源对象ID，采购入库为供应商、销售退货为客户、调整入库为受影响仓库',
    source_party_name VARCHAR(200) NOT NULL DEFAULT '' COMMENT '来源供应商、客户或调整仓库名称快照',
    entry_mode VARCHAR(32) NOT NULL DEFAULT 'SOURCE_GENERATED' COMMENT '录入方式：SOURCE_GENERATED、MANUAL_SUPPLEMENT、MANUAL_ADJUSTMENT',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '仓库名称快照',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRM' COMMENT '状态：DRAFT、PENDING_CONFIRM、CONFIRMED、CANCELLED',
    expected_arrival_date DATE DEFAULT NULL COMMENT '单头预计到货日期',
    confirmed_by_id BIGINT DEFAULT NULL COMMENT '确认人ID',
    confirmed_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '确认人姓名',
    confirmed_at DATETIME DEFAULT NULL COMMENT '确认时间',
    created_by_id BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建人姓名',
    responsible_by_id BIGINT NOT NULL COMMENT '业务负责人ID',
    responsible_by_name VARCHAR(100) NOT NULL COMMENT '业务负责人姓名快照',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    manual_reason VARCHAR(500) NOT NULL DEFAULT '' COMMENT '手工补录或库存调整原因',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inbound_bill_no (inbound_no),
    KEY idx_inbound_bill_source (source_type, source_id),
    KEY idx_inbound_bill_source_no (source_no),
    KEY idx_inbound_bill_party (source_party_id),
    KEY idx_inbound_bill_warehouse (warehouse_id),
    KEY idx_inbound_bill_type_status (inbound_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入库单主表';

CREATE TABLE IF NOT EXISTS inbound_bill_item (
    id BIGINT NOT NULL COMMENT '入库单明细ID',
    inbound_bill_id BIGINT NOT NULL COMMENT '入库单ID',
    inbound_no VARCHAR(64) NOT NULL COMMENT '入库单号冗余',
    source_item_id BIGINT DEFAULT NULL COMMENT '来源单据明细ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码快照',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称快照',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称快照',
    quantity_precision TINYINT NOT NULL DEFAULT 0 COMMENT '数量小数位快照：0-2',
    plan_qty BIGINT NOT NULL DEFAULT 0 COMMENT '来源计划数量，按100倍整数存储',
    processed_qty BIGINT NOT NULL DEFAULT 0 COMMENT '生成本单前累计已入库数量，按100倍整数存储',
    current_qty BIGINT NOT NULL DEFAULT 0 COMMENT '本次入库数量，按100倍整数存储',
    pending_qty BIGINT NOT NULL DEFAULT 0 COMMENT '确认本单后剩余未入库数量，按100倍整数存储',
    qualified_qty BIGINT NOT NULL DEFAULT 0 COMMENT '合格数量，按100倍整数存储；采购入库和销售退货入库使用',
    defective_qty BIGINT NOT NULL DEFAULT 0 COMMENT '不合格数量，按100倍整数存储；采购入库和销售退货入库使用',
    stock_bill_item_id BIGINT DEFAULT NULL COMMENT '确认后生成的库存流水明细ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_inbound_bill_item_bill (inbound_bill_id),
    KEY idx_inbound_bill_item_product (product_id),
    KEY idx_inbound_bill_item_source_item (source_item_id),
    KEY idx_inbound_bill_item_stock_item (stock_bill_item_id),
    CONSTRAINT chk_inbound_bill_item_quantity_precision CHECK (quantity_precision BETWEEN 0 AND 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入库单明细表';

CREATE TABLE IF NOT EXISTS outbound_bill (
    id BIGINT NOT NULL COMMENT '出库单ID',
    outbound_no VARCHAR(64) NOT NULL COMMENT '出库单号',
    outbound_type VARCHAR(32) NOT NULL COMMENT '类型：SALES_OUT、PURCHASE_RETURN、ADJUST_OUT',
    source_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '来源类型：SALES_ORDER、PURCHASE_RETURN_ORDER、STOCK_ADJUST',
    source_id BIGINT DEFAULT NULL COMMENT '来源单据ID',
    source_no VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源单据号',
    source_party_id BIGINT DEFAULT NULL COMMENT '来源对象ID，销售出库为客户、采购退货为供应商、调整出库为受影响仓库',
    source_party_name VARCHAR(200) NOT NULL DEFAULT '' COMMENT '来源客户、供应商或调整仓库名称快照',
    entry_mode VARCHAR(32) NOT NULL DEFAULT 'SOURCE_GENERATED' COMMENT '录入方式：SOURCE_GENERATED、MANUAL_SUPPLEMENT、MANUAL_ADJUSTMENT',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '仓库名称快照',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRM' COMMENT '状态：DRAFT、PENDING_CONFIRM、CONFIRMED、CANCELLED',
    confirmed_by_id BIGINT DEFAULT NULL COMMENT '确认人ID',
    confirmed_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '确认人姓名',
    confirmed_at DATETIME DEFAULT NULL COMMENT '确认时间',
    created_by_id BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建人姓名',
    responsible_by_id BIGINT NOT NULL COMMENT '业务负责人ID',
    responsible_by_name VARCHAR(100) NOT NULL COMMENT '业务负责人姓名快照',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    manual_reason VARCHAR(500) NOT NULL DEFAULT '' COMMENT '手工补录或库存调整原因',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbound_bill_no (outbound_no),
    KEY idx_outbound_bill_source (source_type, source_id),
    KEY idx_outbound_bill_source_no (source_no),
    KEY idx_outbound_bill_party (source_party_id),
    KEY idx_outbound_bill_warehouse (warehouse_id),
    KEY idx_outbound_bill_type_status (outbound_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出库单主表';

CREATE TABLE IF NOT EXISTS outbound_bill_item (
    id BIGINT NOT NULL COMMENT '出库单明细ID',
    outbound_bill_id BIGINT NOT NULL COMMENT '出库单ID',
    outbound_no VARCHAR(64) NOT NULL COMMENT '出库单号冗余',
    source_item_id BIGINT DEFAULT NULL COMMENT '来源单据明细ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码快照',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称快照',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称快照',
    quantity_precision TINYINT NOT NULL DEFAULT 0 COMMENT '数量小数位快照：0-2',
    plan_qty BIGINT NOT NULL DEFAULT 0 COMMENT '来源计划数量，按100倍整数存储',
    processed_qty BIGINT NOT NULL DEFAULT 0 COMMENT '生成本单前累计已出库数量，按100倍整数存储',
    current_qty BIGINT NOT NULL DEFAULT 0 COMMENT '本次出库数量，按100倍整数存储',
    pending_qty BIGINT NOT NULL DEFAULT 0 COMMENT '确认本单后剩余未出库数量，按100倍整数存储',
    stock_bill_item_id BIGINT DEFAULT NULL COMMENT '确认后生成的库存流水明细ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_outbound_bill_item_bill (outbound_bill_id),
    KEY idx_outbound_bill_item_product (product_id),
    KEY idx_outbound_bill_item_source_item (source_item_id),
    KEY idx_outbound_bill_item_stock_item (stock_bill_item_id),
    CONSTRAINT chk_outbound_bill_item_quantity_precision CHECK (quantity_precision BETWEEN 0 AND 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出库单明细表';

CREATE TABLE IF NOT EXISTS stock_bill (
    id BIGINT NOT NULL COMMENT '库存流水凭证ID',
    bill_no VARCHAR(64) NOT NULL COMMENT '库存流水号',
    bill_type VARCHAR(32) NOT NULL COMMENT '类型：PURCHASE_IN、SALES_OUT、PURCHASE_RETURN、SALES_RETURN、ADJUST_IN、ADJUST_OUT',
    direction VARCHAR(16) NOT NULL COMMENT '方向：INBOUND、OUTBOUND',
    source_bill_type VARCHAR(32) NOT NULL COMMENT '来源单类型：INBOUND_BILL、OUTBOUND_BILL',
    source_bill_id BIGINT NOT NULL COMMENT '入库单或出库单ID',
    source_bill_no VARCHAR(64) NOT NULL COMMENT '入库单号或出库单号',
    business_source_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '原业务来源类型',
    business_source_id BIGINT DEFAULT NULL COMMENT '原业务单据ID',
    business_source_no VARCHAR(64) NOT NULL DEFAULT '' COMMENT '原业务单据号',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '仓库名称快照',
    status VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED' COMMENT '状态：CONFIRMED',
    confirmed_by_id BIGINT NOT NULL COMMENT '确认人ID',
    confirmed_by_name VARCHAR(100) NOT NULL COMMENT '确认人姓名',
    confirmed_at DATETIME NOT NULL COMMENT '确认时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_stock_bill_no (bill_no),
    KEY idx_stock_bill_source_bill (source_bill_type, source_bill_id),
    KEY idx_stock_bill_business_source (business_source_type, business_source_id),
    KEY idx_stock_bill_business_source_no (business_source_no),
    KEY idx_stock_bill_warehouse (warehouse_id),
    KEY idx_stock_bill_type_direction (bill_type, direction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存流水凭证主表';

CREATE TABLE IF NOT EXISTS stock_bill_item (
    id BIGINT NOT NULL COMMENT '库存流水凭证明细ID',
    bill_id BIGINT NOT NULL COMMENT '库存流水凭证ID',
    bill_no VARCHAR(64) NOT NULL COMMENT '库存流水号冗余',
    source_bill_item_id BIGINT NOT NULL COMMENT '入库单明细或出库单明细ID',
    business_source_item_id BIGINT DEFAULT NULL COMMENT '原业务来源明细ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码快照',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称快照',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称快照',
    quantity_precision TINYINT NOT NULL DEFAULT 0 COMMENT '数量小数位快照：0-2',
    quantity BIGINT NOT NULL DEFAULT 0 COMMENT '本次入库/出库数量，正数，按100倍整数存储',
    qualified_qty BIGINT NOT NULL DEFAULT 0 COMMENT '合格数量，按100倍整数存储；仅质检适用类型使用',
    defective_qty BIGINT NOT NULL DEFAULT 0 COMMENT '不合格数量，按100倍整数存储；仅质检适用类型使用',
    before_qty BIGINT NOT NULL DEFAULT 0 COMMENT '变动前库存，按100倍整数存储',
    change_qty BIGINT NOT NULL DEFAULT 0 COMMENT '库存变动数量，入库为正、出库为负，按100倍整数存储',
    after_qty BIGINT NOT NULL DEFAULT 0 COMMENT '变动后库存，按100倍整数存储',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_stock_bill_item_bill (bill_id),
    KEY idx_stock_bill_item_product (product_id),
    KEY idx_stock_bill_item_source_item (source_bill_item_id),
    KEY idx_stock_bill_item_business_source_item (business_source_item_id),
    CONSTRAINT chk_stock_bill_item_quantity_precision CHECK (quantity_precision BETWEEN 0 AND 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存流水凭证明细表';
