-- MVP 供应商采购库表设计：极简版
-- 数据库：MySQL 8
-- 说明：主键由 MyBatis-Plus ASSIGN_ID 生成，因此不使用 AUTO_INCREMENT。

CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_code VARCHAR(64) NOT NULL COMMENT '供应商编码',
    supplier_name VARCHAR(200) NOT NULL COMMENT '供应商名称',
    contact_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '联系人',
    contact_phone VARCHAR(32) NOT NULL DEFAULT '' COMMENT '联系电话',
    address VARCHAR(255) NOT NULL DEFAULT '' COMMENT '地址',
    payment_terms VARCHAR(100) NOT NULL DEFAULT '' COMMENT '付款条件',
    overall_score INT NOT NULL DEFAULT 0 COMMENT '综合评分，放大100倍保存，10000表示100.00',
    delivery_score INT NOT NULL DEFAULT 0 COMMENT '交付评分，放大100倍保存，10000表示100.00',
    quality_score INT NOT NULL DEFAULT 0 COMMENT '质量评分，放大100倍保存，10000表示100.00',
    price_score INT NOT NULL DEFAULT 0 COMMENT '价格评分，放大100倍保存，10000表示100.00',
    service_score INT NOT NULL DEFAULT 0 COMMENT '服务评分，放大100倍保存，10000表示100.00',
    avg_delivery_days DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '平均交付天数',
    on_time_rate INT NOT NULL DEFAULT 0 COMMENT '准时交付率，放大100倍保存，10000表示100.00%',
    qualified_rate INT NOT NULL DEFAULT 0 COMMENT '到货合格率，放大100倍保存，10000表示100.00%',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常，1删除',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_code (supplier_code),
    KEY idx_supplier_name (supplier_name),
    KEY idx_supplier_score (overall_score),
    KEY idx_supplier_deleted_status (deleted, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商表';

CREATE TABLE IF NOT EXISTS supplier_product (
    id BIGINT NOT NULL COMMENT '供应商供货产品ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_code VARCHAR(64) NOT NULL COMMENT '供应商编码冗余',
    supplier_name VARCHAR(200) NOT NULL COMMENT '供应商名称冗余',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码冗余',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称冗余',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称冗余',
    supplier_product_code VARCHAR(100) NOT NULL DEFAULT '' COMMENT '供应商侧产品编码',
    latest_purchase_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '最近采购单价',
    min_order_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '最小起订量',
    lead_time_days INT NOT NULL DEFAULT 0 COMMENT '预计交期天数',
    delivery_score INT NOT NULL DEFAULT 0 COMMENT '该产品维度交付评分，放大100倍保存，10000表示100.00',
    quality_score INT NOT NULL DEFAULT 0 COMMENT '该产品维度质量评分，放大100倍保存，10000表示100.00',
    price_score INT NOT NULL DEFAULT 0 COMMENT '该产品维度价格评分，放大100倍保存，10000表示100.00',
    ai_score INT NOT NULL DEFAULT 0 COMMENT 'AI/规则综合推荐分，放大100倍保存，10000表示100.00',
    last_purchase_at DATETIME DEFAULT NULL COMMENT '最近采购时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常，1删除',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_product (supplier_id, product_id),
    KEY idx_supplier_product_product (product_id),
    KEY idx_supplier_product_score (product_id, ai_score),
    KEY idx_supplier_product_deleted_status (deleted, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商供货产品表';

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT NOT NULL COMMENT '采购订单ID',
    purchase_no VARCHAR(64) NOT NULL COMMENT '采购单号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_code VARCHAR(64) NOT NULL COMMENT '供应商编码冗余',
    supplier_name VARCHAR(200) NOT NULL COMMENT '供应商名称冗余',
    warehouse_id BIGINT NOT NULL COMMENT '目标入库仓库ID',
    warehouse_name VARCHAR(100) NOT NULL COMMENT '目标入库仓库名称冗余',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT、SUBMITTED、APPROVED、PARTIAL_INBOUND、INBOUND_DONE、CANCELLED',
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
    expected_arrival_date DATE DEFAULT NULL COMMENT '预计到货日期',
    created_by_id BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建人姓名',
    submitted_at DATETIME DEFAULT NULL COMMENT '提交时间',
    approved_by_id BIGINT DEFAULT NULL COMMENT '审核人ID',
    approved_by_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '审核人姓名',
    approved_at DATETIME DEFAULT NULL COMMENT '审核时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常，1删除',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_order_no (purchase_no),
    KEY idx_purchase_order_supplier (supplier_id),
    KEY idx_purchase_order_warehouse (warehouse_id),
    KEY idx_purchase_order_status (status),
    KEY idx_purchase_order_create_time (create_time),
    KEY idx_purchase_order_deleted_status (deleted, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购订单主表';

CREATE TABLE IF NOT EXISTS purchase_order_item (
    id BIGINT NOT NULL COMMENT '明细ID',
    purchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    purchase_no VARCHAR(64) NOT NULL COMMENT '采购单号冗余',
    supplier_product_id BIGINT DEFAULT NULL COMMENT '供应商供货产品ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) NOT NULL COMMENT '产品编码冗余',
    product_name VARCHAR(200) NOT NULL COMMENT '产品名称冗余',
    unit_name VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '单位名称冗余',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '采购数量',
    inbound_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '已入库数量',
    unit_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '采购单价',
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '明细金额',
    selected_supplier_score INT NOT NULL DEFAULT 0 COMMENT '下单时供应商推荐分快照，放大100倍保存，10000表示100.00',
    expected_arrival_date DATE DEFAULT NULL COMMENT '明细预计到货日期',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_purchase_order_item_order (purchase_order_id),
    KEY idx_purchase_order_item_product (product_id),
    KEY idx_purchase_order_item_supplier_product (supplier_product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购订单明细表';
